
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epohdppkbxfflbfowaic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwb2hkcHBrYnhmZmxiZm93YWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTgzNjcsImV4cCI6MjA1OTg5NDM2N30.UO9mNePG6jgDqLQ3gHa3BduFNp2eNaNk2mJZFBqK2O8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper functions for route data
export const routesTable = {
  getAll: async () => {
    const { data, error } = await supabase
      .from('routes')
      .select('*');
    
    if (error) throw error;
    return data || [];
  },
  
  getById: async (id: string) => {
    const { data, error } = await supabase
      .from('routes')
      .select('*')
      .eq('id', id)
      .single();
    
    if (error) throw error;
    return data;
  },
  
  create: async (routeData: any) => {
    const { data, error } = await supabase
      .from('routes')
      .insert([routeData])
      .select()
      .single();
    
    if (error) throw error;
    return data;
  },
  
  update: async (id: string, routeData: any) => {
    const { data, error } = await supabase
      .from('routes')
      .update(routeData)
      .eq('id', id)
      .select()
      .single();
    
    if (error) throw error;
    return data;
  },
  
  delete: async (id: string) => {
    const { error } = await supabase
      .from('routes')
      .delete()
      .eq('id', id);
    
    if (error) throw error;
    return true;
  }
};
